# This file was generated by GoReleaser. DO NOT EDIT.
cask "visr" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "8ea5f101073272e8b77cf12c989f8816e5403779a20f220d82a2aaf1656f989f"
      url "https://visr-releases.s3.amazonaws.com/#{version}/visr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef1ea28fb8a46e20c65b5fcfd3e178db8a42a8e07583efe4b09550fed375b080"
      url "https://visr-releases.s3.amazonaws.com/#{version}/visr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a37fee2399805c12deae8c3a56d5a51019da78cdfa4b3f40ee5726457c80a3c6"
      url "https://visr-releases.s3.amazonaws.com/#{version}/visr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00ec2bfd1f887d7551b1c79b5a8b5d915d21ef1344c5fa60c38e7bcaf4e0a648"
      url "https://visr-releases.s3.amazonaws.com/#{version}/visr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "visr"
  desc "Agent UX testing - Agents Are the New Browsers"
  homepage "https://visr.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "visr"

  # No zap stanza required

end
