# This file was generated by GoReleaser. DO NOT EDIT.
cask "visr" do
  version "0.1.1-rc.0"

  on_macos do
    on_intel do
      sha256 "72c2a6e1579a6e4d65101908de27fa2859656bad198997b0319abbe3de14eaba"
      url "https://visr-releases.s3.amazonaws.com/#{version}/visr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec99427d12c542f6e1f0b3c66944860ede3abb5b78f0a0e6c59cd933ea0e6d06"
      url "https://visr-releases.s3.amazonaws.com/#{version}/visr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5209a020988ecbe558f419bdc6931289483433d6763dc7e65a9a527318f1e88e"
      url "https://visr-releases.s3.amazonaws.com/#{version}/visr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "290b2809f9a86eb997916a4fb956ca425d08539236f8baf1e49098a4eea10cf9"
      url "https://visr-releases.s3.amazonaws.com/#{version}/visr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "visr"
  desc "Agent UX testing - Agents Are the New Browsers"
  homepage "https://visr.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "visr"

  # No zap stanza required

end
