# This file was generated by GoReleaser. DO NOT EDIT.
cask "visr" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "4a3f987e653c323a6f305b36ded0ac825f57a1e983225c75f73b996e27ac49a4"
      url "https://visr-releases.s3.amazonaws.com/#{version}/visr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "007ccb87a743ee813595d4fa5d78b4d69adb17b250ae0985d03508699f4772d4"
      url "https://visr-releases.s3.amazonaws.com/#{version}/visr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b8ebf315d394bc7e543e1906dca29723d3958a32e1af78c5201a3e343304f4cd"
      url "https://visr-releases.s3.amazonaws.com/#{version}/visr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f36eb0699b38a964528d606e7e3784d5bbec731c5ae56f9f96f5adac86a1b1e0"
      url "https://visr-releases.s3.amazonaws.com/#{version}/visr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "visr"
  desc "Agent UX testing - Agents Are the New Browsers"
  homepage "https://visr.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "visr"

  # No zap stanza required

end
