# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Visr < Formula
  desc "Agent UX testing - Agents Are the New Browsers"
  homepage "https://visr.dev"
  version "0.3.2"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://visr-releases.s3.amazonaws.com/0.3.2/visr_0.3.2_darwin_amd64.tar.gz"
      sha256 "1cd388c7a6139384a75a61052932a0ef23cc3a368531f3985c03030cb91ef54a"

      define_method(:install) do
        bin.install "visr"
      end
    end
    if Hardware::CPU.arm?
      url "https://visr-releases.s3.amazonaws.com/0.3.2/visr_0.3.2_darwin_arm64.tar.gz"
      sha256 "596494cc833ddcfe744c75acee5b3426f1e266815eabe84fb83c80ca83a5ea84"

      define_method(:install) do
        bin.install "visr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://visr-releases.s3.amazonaws.com/0.3.2/visr_0.3.2_linux_amd64.tar.gz"
      sha256 "b450b7efe3f484ae5c5da3dc9c13aa67e170a399ac5bb6974775818eb1e64dd8"
      define_method(:install) do
        bin.install "visr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://visr-releases.s3.amazonaws.com/0.3.2/visr_0.3.2_linux_arm64.tar.gz"
      sha256 "abc722af923c713ea15aa74e12d87ae689ef04e949d28f431d58c99d672a0454"
      define_method(:install) do
        bin.install "visr"
      end
    end
  end

  test do
    system "#{bin}/visr", "version"
  end
end
