# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Visr < Formula
  desc "Agent UX testing - Agents Are the New Browsers"
  homepage "https://visr.dev"
  version "0.0.19"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://visr-releases.s3.amazonaws.com/0.0.19/visr_0.0.19_darwin_amd64.tar.gz"
      sha256 "62d42b8befdb696919d63a5b2b382156684d0c8d60e4c1eaba42b7711f8f30a5"

      define_method(:install) do
        bin.install "visr"
      end
    end
    if Hardware::CPU.arm?
      url "https://visr-releases.s3.amazonaws.com/0.0.19/visr_0.0.19_darwin_arm64.tar.gz"
      sha256 "b8c2e1090e8b50c45f966237f28e7a737fc9a98d945a7abf41553370652e0915"

      define_method(:install) do
        bin.install "visr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://visr-releases.s3.amazonaws.com/0.0.19/visr_0.0.19_linux_amd64.tar.gz"
      sha256 "fd4e4ef53a0c1f628cb54e5090f756e407786dfcd341f609799ca680a162ee3a"
      define_method(:install) do
        bin.install "visr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://visr-releases.s3.amazonaws.com/0.0.19/visr_0.0.19_linux_arm64.tar.gz"
      sha256 "9de581fe5aab99c26cdfa3d0a424a3b5ed5ee87f30b5becaed6f34f2e9a54ec6"
      define_method(:install) do
        bin.install "visr"
      end
    end
  end

  test do
    system "#{bin}/visr", "version"
  end
end
