# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Visr < Formula
  desc "Agent UX testing - Agents Are the New Browsers"
  homepage "https://visr.dev"
  version "0.0.8"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://visr-releases.s3.amazonaws.com/0.0.8/visr_0.0.8_darwin_amd64.tar.gz"
      sha256 "38f37f641a9cb6e53769b5cb37211006323ab349caf02d4bb1b8fb5fa35ebc2c"

      define_method(:install) do
        bin.install "visr"
      end
    end
    if Hardware::CPU.arm?
      url "https://visr-releases.s3.amazonaws.com/0.0.8/visr_0.0.8_darwin_arm64.tar.gz"
      sha256 "f4f2e742c183cb585aedfec19735ae962b9ed7ed62fefa305ba86e7fce99f429"

      define_method(:install) do
        bin.install "visr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://visr-releases.s3.amazonaws.com/0.0.8/visr_0.0.8_linux_amd64.tar.gz"
      sha256 "538562577e495873ca843a9c4d211db89001c37c65b63afc22375e9b28f249c5"
      define_method(:install) do
        bin.install "visr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://visr-releases.s3.amazonaws.com/0.0.8/visr_0.0.8_linux_arm64.tar.gz"
      sha256 "bcc44c758e3e1b0c429301bd744f769024bfa1117a772a173a6e49d255975fc7"
      define_method(:install) do
        bin.install "visr"
      end
    end
  end

  test do
    system "#{bin}/visr", "version"
  end
end
